services:
  psychologist:
    build: .
    container_name: psych-bot-psychologist
    restart: unless-stopped
    env_file: .env
    command: node psychologist.js
    volumes:
        - ./data/psychologist:/app/data  # Монтируем том для памяти психолога
    #   - ./logs/psychologist:/app/logs  # Если нужны логи

  sexologist:
    build: .
    container_name: psych-bot-sexologist
    restart: unless-stopped
    env_file: .env
    command: node sexologist.js
    volumes:
        - ./data/sexologist:/app/data    # Монтируем том для памяти сексолога
    #   - ./logs/sexologist:/app/logs    # Если нужны логи
